<!DOCTYPE html>
<head>
<title>Form</title>
<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

<!-- import jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<!-- Google Icon Font -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- http://materializecss.com -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

<!-- custom JavaScript and CSS -->
<script src="/../js/main.js"></script>
<!-- <link rel="stylesheet" type="text/css" href="/css/main.css"/> -->
<link rel="stylesheet" type="text/css" href="/css/theme_one.css"/>

</head>
<body>

<div class="row">
    <form action="/postForm" method="POST" class="col s12">
        <div class="row">
            <div class="input-field col s6">
                <input name="first_name" placeholder="Placeholder" id="first_name" type="text" class="validate">
                <label for="first_name">First Name</label>
            </div>
        </div>
        
        <div class="row">
            <div class="input-field col s6">
                <input class="btn custom_btn" type="submit" value="Submit">
            </div>
        </div>
    </form>
</div>
       

</body>
</html>
