<!DOCTYPE html>
<head>
<title>SMU Technology Survey</title>
<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

<!-- import jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<!-- Google Icon Font -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- http://materializecss.com -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
<!-- custom JavaScript and CSS -->

<!-- main js file -->
<script src="/../js/main.js"></script>

<!-- random theme: inherited from materialize.css -->
<link rel="stylesheet" type="text/css" href="/css/theme_one.css"/>
<!-- main stylesheet -->
<link rel="stylesheet" type="text/css" href="/css/main.css"/>

<script>
$(document).ready(function(){
	// initialize select form elements
	$('select').formSelect();
});
</script>

</head>
<body>

<div class="row">
	<form id="mainForm" action="/postForm" method="POST" class="col s12">
<!--         <div class="page" id="page1">
            <div class="row">
				<div class="progress">
					<div class="indeterminate"></div>
				</div>
            </div>	
            <div class="row">
                <div class="input-field col s12">
                    <input id="email" name="email" type="email" class="validate" required>
                    <label for="email">Email</label>
                    <span class="helper-text">Please enter a valid SMU email.</span>
                </div>
            </div>
        </div> end page 1 -->

		<div class="page" id="page2">
		    <div class="row">
		        <h6>1. How often do you use a desktop or laptop computer?  </h6>
		        <div class="input-field col s12">
		            <select name="1.1" required="required" class="validate invalid">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">More than 5 hours a day</option>
		                <option value="2">Less than 5 hours a day</option>
		                <option value="3">Not everyday</option>
		            </select>
		            <span style="opacity:0;color:#f44336;" class="helper-text">Please select an option.</span>
		        </div>
		    </div>

		    <div class="row">
		        <h6>2. What kind of computer do you own?  </h6>
		        <div class="input-field col s12">
		            <select name="1.2">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Mac (MacOS/OSX)</option>
		                <option value="2">PC (Windows)</option>
		                <option value="3">Linux</option>
		                <option value="4">I'm not sure.</option>
		                <option value="5">I don't own a computer. </option>
		            </select>
		            <span style="opacity:0;color:#f44336;" class="helper-text">Please select an option.</span>
		        </div>
		    </div>

		    <div class="row">
		        <h6>3. What kind of smartphone do you use? </h6>
		        <div class="input-field col s12">
		            <select name="1.3">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">iPhone</option>
		                <option value="2">Android</option>
		                <option value="3">I don't own a smartphone.</option>
		            </select>
		            <span style="opacity:0;color:#f44336;" class="helper-text">Please select an option.</span>
		        </div>
		    </div>

		    <div class="row">
		        <h6>4. How technologically savy are you? </h6>
		        <div class="input-field col s12">
		            <select name="1.4">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Expert</option>
		                <option value="2">Intermediate</option>
		                <option value="3">Beginner</option>
		                <option value="4">I'm not sure</option>
		            </select>
		            <span style="opacity:0;color:#f44336;" class="helper-text">Please select an option.</span>
		        </div>
		    </div>

		    <div class="row">
		        <h6>5. How relevant is technology to your major? </h6>
		        <div class="input-field col s12">
		            <select name="1.5">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Extremely relevant</option>
		                <option value="2">Somewhat relevant</option>
		                <option value="3">Not very relevant</option>
		                <option value="4">Not at all relevant</option>
		            </select>
		            <span style="opacity:0;color:#f44336;" class="helper-text">Please select an option.</span>
		        </div>
		    </div>

		    <div class="row">
		        <h6>6. Which of the following technical tasks are you comfortable doing?</h6>
		        <div class="input-field col s12">
		            <select name="1.6" multiple >
		                <option value="" disabled selected>Select all that apply</option>
		                <option value="1">Typing a paper in Word</option>
		                <option value="2">Using a classroom projector</option>
		                <option value="3">Compiling and running Java code</option>
		                <option value="4">Using the printers in Fondren</option>
		                <option value="5">Buying items online</option>
		                <option value="6">Python list comprehension</option>
		            </select>
		            <span style="opacity:0;color:#f44336;" class="helper-text">Please select an option.</span>
		        </div>
		    </div>

		</div><!-- end page 2 -->

		<div class="page" id="page3">
		    <div class="row">
		        <h6>1. What school do you attend?  </h6>
		        <div class="input-field col s12">
		            <select name="2.1">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Dedman</option>
		                <option value="2">Dedman Law</option>
		                <option value="3">Meadows</option>
		                <option value="4">Cox</option>
		                <option value="5">Lyle</option>
		                <option value="6">Perkins</option>
		                <option value="7">Simmons</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>2. What year are you?  </h6>
		        <div class="input-field col s12">
		            <select name="2.2">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Undergraduate</option>
		                <option value="2">Graduate</option>
		                <option value="3">PhD Candidate</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>3. What's your gender?  </h6>
		        <div class="input-field col s12">
		            <select name="2.3">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Male</option>
		                <option value="2">Female</option>
		                <option value="3">Other</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>4. How old are you?  </h6>
		        <div class="input-field col s12">
		            <select name="2.4">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">17-19</option>
		                <option value="2">20-22</option>
		                <option value="3">23-25</option>
		                <option value="4">25+</option>
		            </select>
		        </div>
		    </div>
		</div><!-- end page 3 -->

		<div class="page" id="page4">
		    <div class="row">
		        <h6>1. How rushed did you feel while competing this form?  </h6>
		        <div class="input-field col s12">
		            <select name="3.1">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Very rushed</option>
		                <option value="2">Somewhat rushed</option>
		                <option value="3">Not very rushed</option>
		                <option value="4">Not at all rushed</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>2. How mentally demanding was filling out this task?  </h6>
		        <div class="input-field col s12">
		            <select name="3.2">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Very demanding</option>
		                <option value="2">Somewhat demanding</option>
		                <option value="3">Not very demanding</option>
		                <option value="4">Not at all demanding</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>3. How many questions did you find difficult to answer?  </h6>
		        <div class="input-field col s12">
		            <select name="3.3">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Very difficult</option>
		                <option value="2">Somewhat difficult</option>
		                <option value="3">Not very difficult</option>
		                <option value="4">Not at all difficult</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>4. How frustrated or discouraged were you while completing this form?  </h6>
		        <div class="input-field col s12">
		            <select name="3.4">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Very frustrated</option>
		                <option value="2">Somewhat frustrated</option>
		                <option value="3">Not very frustrated</option>
		                <option value="4">Not at all frustrated</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>5. How happy were you completing this form?  </h6>
		        <div class="input-field col s12">
		            <select name="3.5">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Happy</option>
		                <option value="2">Somewhat happy</option>
		                <option value="3">Neutral </option>
		                <option value="4">Unhappy</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>6. How likely are you to share this form?  </h6>
		        <div class="input-field col s12">
		            <select name="3.6">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">Very likely</option>
		                <option value="2">Somewhat likely</option>
		                <option value="3">Not very likely</option>
		                <option value="4">Not at all likely</option>
		            </select>
		        </div>
		    </div>

		    <div class="row">
		        <h6>7. What was the first question in this form?  </h6>
		        <div class="input-field col s12">
		            <select name="3.7">
		                <option value="" disabled selected>Select one</option>
		                <option value="1">How often do you use a desktop or laptop computer?</option>
		                <option value="2">What school do you attend?</option>
		                <option value="3">How technologically savy are you?</option>
		            </select>
		        </div>
		    </div>
		</div><!-- end page 4 -->

        <div style="overflow:auto;">
            <div style="float:right;">
                <button class="btn" type="button" id="nextBtn">Next</button>
            </div>
        </div>
    </form>
</div>

<!-- logic for multi-page form behavior -->
<script src="/../js/multi-page-form.js"></script>
</body>
</html>