<!DOCTYPE html>
<head>
<title>Responses Submitted</title>
<!-- random theme: inherited from materialize.css -->
<link rel="stylesheet" type="text/css" href="/AB-Testing-Form/public/css/materialize.css"/>
<link rel="stylesheet" type="text/css" href="/AB-Testing-Form/public/css/main.css"/>
<!-- main stylesheet -->

<style type="text/css">
body {
	padding-left: 15px;
}

h5, h6 {
	margin-left: 25px;
	margin-right: 25px;
}

</style>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
	<div class="container z-depth-2">
		<div class="row heading">
			<h3>SMU Technology Survey</h3>
		</div>
		<div class="row">
			<h5>Thank you. Your response has been recorded.</h5><br>
			<h6>You will be contacted if you are selected to receive a Starbucks giftcard.</h6><br>
		</div>
	</div>
</html>