<!DOCTYPE html>
<head>
<title>Responses Submitted</title>
<!-- random theme: inherited from materialize.css -->
<link rel="stylesheet" type="text/css" href="/css/theme_one.css"/>
<!-- main stylesheet -->

<style type="text/css">
body {
	padding-left: 15px;
}

</style>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
<h6>Thank you. Your responses have been recorded.</h6>
<p>You may close this window.</p>
</body>
</html>