<!DOCTYPE html>
<head>
<title>Responses Submitted</title>
<!-- random theme: inherited from materialize.css -->
<link rel="stylesheet" type="text/css" href="/css/materialize.css"/>
<link rel="stylesheet" type="text/css" href="/css/main.css"/>
<!-- main stylesheet -->

<style type="text/css">
body {
	padding-left: 15px;
}

</style>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
	<div class="container z-depth-2">
		<div class="row">
			<h3>SMU Technology Survey</h3>
			<div class="heading-divider col s12"></div><br><br>
			<h6>Thank you. Your responses have been recorded.</h6>
		</div>
	</div>
</body>
</html>